name: Nexus CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-11 build-essential

      - name: Build & Test Base Engine (Standard C++)
        working-directory: ./Cpp_Neural_Network_Base
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Build Optimized Engine (AVX-512)
        working-directory: ./Cpp_Neural_Network_Main
        # We use continue-on-error because GitHub CPUs lack AVX-512 hardware
        continue-on-error: true
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh
